# docker-compose.ci.yml

version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'

  klikdat-app: 
    image: $DOCKER_USERNAME/dockerizing-nodejs-klikdat-app:latest 
    command: "npn run migrate && npm start" 
    environment: 
      DB_SCHEMA: postgres 
      DB_USER: postgres 
      DB_PASSWORD: postgres 
      DB_HOST: postgres 
      DATABASE_URL: postgres://postgres:postgres@postgres:5432
      JWT_SECRET: nodeauthsecret
    depends_on: 
      - postgres 
    ports: 
      - '3000:3000'

# docker-compose.ci.yml 
