# docker-compose.yml

version: "3.7"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - '5432:5432'
    volumes:
      - $HOME/development/database/data:/var/lib/postgresql/data

  klikdat-app:
    build:
      context: .
    environment:      
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/klikdat
    depends_on:
      - postgres
    ports:
      - '3000:3000'
        
